services:
  web:
    image: "investing-backend-rs"
    ports:
      - "8080:8080"
    profiles: ["deployed"]
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    environment:
      POSTGRES_DB: compoundfoliodb
      POSTGRES_USER: compoundfoliodbadmin
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-example}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compoundfoliodbadmin -d compoundfoliodb"]
      interval: 1s
      timeout: 5s
      retries: 10

