name: 'Build'

# **What it does**: Builds backend application and deploys it to our VPS
# **Why we have it**: To automate CI/CD pipeline of our test environment

on:
  workflow_dispatch:
      
permissions:
  contents: read
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      MODULE_NAME: 'investing-backend-rs'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Decrypt configuration
        run: |
          ./decrypt-config.sh dev
          ./decrypt-config.sh prod
        env:
          CONFIGURATION_PASSWORD: ${{ secrets.CONFIGURATION_PASSWORD }}
      - name: Build image
        run: docker build -t ${MODULE_NAME}:${{ github.run_id }} -t ${MODULE_NAME}:latest .
      - name: Save image
        run: docker save -o $MODULE_NAME.tar "${MODULE_NAME}:latest"
      - name: Save image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ${{ env.MODULE_NAME }}.tar
      - name: Save the compose file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose
          path: docker-compose.yml

  deploy-dev:
    name: Deploy to dev
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      module_name: 'investing-backend-rs'
      env_name: dev

  deploy-prod:
    name: Deploy to prod
    needs: deploy-dev
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      module_name: 'investing-backend-rs'
      env_name: prod
