name: 'Build'

# **What it does**: Builds backend application and deploys it to our VPS
# **Why we have it**: To automate CI/CD pipeline of our test environment

on:
  workflow_dispatch:
      
permissions:
  contents: read
  
env:
  MODULE_NAME: 'investing-backend-rs'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      module_name: ${{ steps.outputting.outputs.module_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Decrypt configuration
        run: ./decrypt-config.sh prod
        env:
          CONFIGURATION_PASSWORD: ${{ secrets.CONFIGURATION_PASSWORD }}
      - name: Build image
        run: docker build -t $MODULE_NAME .
      - name: Save image
        run: docker save -o $MODULE_NAME.tar "${MODULE_NAME}:latest" # TODO: tag
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ${{ env.MODULE_NAME }}.tar
      - name: Store output for deployment
        id: outputting
        run: echo "module_name=$MODULE_NAME" >> "$GITHUB_OUTPUT"

  deploy-dev:
    name: Deploy Dev
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      module_name: ${{ needs.vars.outputs.module_name }}
      env_name: dev

  deploy-prod:
    name: Deploy Prod
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      module_name: ${{ needs.vars.outputs.module_name }}
      env_name: prod
